{{- with .Values.config }}
log_level: {{ .logLevel }}
server:
  port: {{ .server.port }}
  debug: false
  name_space: "wallet"
  read_timeout: "100s"
  write_timeout: "100s"
  idle_timeout: "100s"
database:
  connection-address: {{ .database.connectionAddress }}
  log_level: {{ .database.logLevel }}
  connect-timeout: 5s
  connection-lifetime: 10m
  max-open-connections: 100
  max-idle-connections: 50
{{ end }}